language: en
pipeline:
- name: WhitespaceTokenizer
- name: LanguageModelFeaturizer
  model_name: "bert"
  model_weights: "bert-base-multilingual-cased"
  framework: "pt"
- name: DIETClassifier
  epochs: 200
- name: FallbackClassifier
  threshold: 0.5

policies:
- name: MemoizationPolicy
- name: TEDPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_custom_fallback"
  enable_fallback_prediction: True

# policies:
#   - name: MemoizationPolicy
#   - name: RulePolicy
#     core_fallback_threshold: 0.3
#     core_fallback_action_name: "action_default_fallback"
#     enable_fallback_prediction: true
#   - name: UnexpecTEDIntentPolicy
#     max_history: 10
#   - name: TEDPolicy
#     max_history: 10
#     epochs: 100

assistant_id: 20250620-134332-cautious-touch

